class Attraction {
  final String id;
  final String name;
  final String nameAr;
  final String description;
  final String descriptionAr;
  final String imageUrl;
  final String category;
  final double distance;
  final String openingHours;
  final String openingHoursAr;
  final double latitude;
  final double longitude;
  final double rating;
  final String mapsUrl;

  Attraction({
    required this.id,
    required this.name,
    required this.nameAr,
    required this.description,
    required this.descriptionAr,
    required this.imageUrl,
    required this.category,
    required this.distance,
    required this.openingHours,
    required this.openingHoursAr,
    required this.latitude,
    required this.longitude,
    required this.rating,
    required this.mapsUrl,
  });

  /// Create a copy of this attraction with updated distance
  Attraction copyWith({
    String? id,
    String? name,
    String? nameAr,
    String? description,
    String? descriptionAr,
    String? imageUrl,
    String? category,
    double? distance,
    String? openingHours,
    String? openingHoursAr,
    double? latitude,
    double? longitude,
    double? rating,
    String? mapsUrl,
  }) {
    return Attraction(
      id: id ?? this.id,
      name: name ?? this.name,
      nameAr: nameAr ?? this.nameAr,
      description: description ?? this.description,
      descriptionAr: descriptionAr ?? this.descriptionAr,
      imageUrl: imageUrl ?? this.imageUrl,
      category: category ?? this.category,
      distance: distance ?? this.distance,
      openingHours: openingHours ?? this.openingHours,
      openingHoursAr: openingHoursAr ?? this.openingHoursAr,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      rating: rating ?? this.rating,
      mapsUrl: mapsUrl ?? this.mapsUrl,
    );
  }

  static List<Attraction> dummyAttractions = [
    Attraction(
      id: '1',
      name: 'Al-Masjid an-Nabawi',
      nameAr: 'المسجد النبوي',
      description:
          'The Prophet\'s Mosque in Medina, one of the largest mosques in the world',
      descriptionAr:
          'المسجد النبوي في المدينة المنورة، أحد أكبر المساجد في العالم',
      imageUrl: 'assets/images/mecca.jpg',
      category: 'heritage',
      distance: 2.5,
      openingHours: 'Open 24 hours',
      openingHoursAr: 'مفتوح 24 ساعة',
      latitude: 24.4672,
      longitude: 39.6111,
      rating: 4.9,
      mapsUrl: 'https://maps.app.goo.gl/qtrinxKHnqYJYnzR8',
    ),
    Attraction(
      id: '2',
      name: 'Al Balad Historic District',
      nameAr: 'حي البلد التاريخي',
      description: 'Historic area of Jeddah with traditional architecture',
      descriptionAr: 'منطقة تاريخية في جدة بعمارة تقليدية',
      imageUrl: 'assets/images/balad.jpg',
      category: 'heritage',
      distance: 12.8,
      openingHours: '10:00 AM - 10:00 PM',
      openingHoursAr: '10:00 صباحاً - 10:00 مساءً',
      latitude: 21.4858,
      longitude: 39.1925,
      rating: 4.6,
      mapsUrl: 'https://www.google.com/maps?q=21.4858,39.1925',
    ),
    Attraction(
      id: '3',
      name: 'Hegra Archaeological Site',
      nameAr: 'موقع الحجر الأثري',
      description: 'Ancient Nabataean city with stunning rock-cut tombs',
      descriptionAr: 'مدينة نبطية قديمة بمقابر منحوتة في الصخر',
      imageUrl: 'assets/images/hegra.jpg',
      category: 'heritage',
      distance: 380.0,
      openingHours: '8:00 AM - 5:00 PM',
      openingHoursAr: '8:00 صباحاً - 5:00 مساءً',
      latitude: 26.7891,
      longitude: 37.9547,
      rating: 4.9,
      mapsUrl: 'https://www.google.com/maps?q=26.7891,37.9547',
    ),
    Attraction(
      id: '4',
      name: 'Khaleelah Restaurant',
      nameAr: 'مطعم خليلة',
      description: 'Traditional restaurant in Jeddah',
      descriptionAr: 'مطعم تقليدي في جدة',
      imageUrl: 'assets/images/khalila.jpg',
      category: 'food',
      distance: 1.2,
      openingHours: '12:00 PM - 11:00 PM',
      openingHoursAr: '12:00 ظهراً - 11:00 مساءً',
      latitude: 21.5884033,
      longitude: 39.1057039,
      rating: 3.1,
      mapsUrl: 'https://maps.app.goo.gl/revwGwUXZd3Z7svGA',
    ),

    Attraction(
      id: '5',
      name: 'Alya Restaurant',
      nameAr: 'مطعم أليا',
      description: 'Restaurant in Jeddah',
      descriptionAr: 'مطعم في جدة',
      imageUrl: 'assets/images/alya.jpg',
      category: 'food',
      distance: 1.0,
      openingHours: '12:00 PM - 11:00 PM',
      openingHoursAr: '12:00 ظهراً - 11:00 مساءً',
      latitude: 21.5879828,
      longitude: 39.1057407,
      rating: 3.6,
      mapsUrl: 'https://maps.app.goo.gl/BCYJyY7GUd7dhpzq5',
    ),
    Attraction(
      id: '6',
      name: 'Il Gibiano Restaurant',
      nameAr: 'مطعم إلجبيانو',
      description: 'Italian restaurant in Jeddah',
      descriptionAr: 'مطعم إيطالي في جدة',
      imageUrl: 'assets/images/elgapino.jpg',
      category: 'food',
      distance: 1.0,
      openingHours: '12:00 PM - 11:00 PM',
      openingHoursAr: '12:00 ظهراً - 11:00 مساءً',
      latitude: 21.5918835,
      longitude: 39.1068179,
      rating: 4.2,
      mapsUrl: 'https://maps.app.goo.gl/A6q3EJXcrwULRMbg8',
    ),
    Attraction(
      id: '7',
      name: 'Sympl Burger',
      nameAr: 'سمبل برقر',
      description: 'Burger restaurant in Jeddah',
      descriptionAr: 'مطعم برجر في جدة',
      imageUrl: 'assets/images/simple_burger.jpeg',
      category: 'food',
      distance: 1.5,
      openingHours: '12:00 PM - 12:00 AM',
      openingHoursAr: '12:00 ظهراً - 12:00 صباحاً',
      latitude: 21.5938657,
      longitude: 39.1309733,
      rating: 4.2,
      mapsUrl: 'https://maps.app.goo.gl/ktNrTViL25PFUDxg6',
    ),
    Attraction(
      id: '8',
      name: 'Lovera Restaurant',
      nameAr: 'مطعم لوفيرا',
      description: 'Restaurant in Jeddah',
      descriptionAr: 'مطعم في جدة',
      imageUrl: 'assets/images/lovera.jpg',
      category: 'food',
      distance: 2.0,
      openingHours: '12:00 PM - 11:00 PM',
      openingHoursAr: '12:00 ظهراً - 11:00 مساءً',
      latitude: 21.5108066,
      longitude: 39.2324958,
      rating: 4.1,
      mapsUrl: 'https://maps.app.goo.gl/y8t2kzRPydyZDgqV9',
    ),
    Attraction(
      id: '9',
      name: "McDonald's",
      nameAr: 'ماكدونالدز',
      description: 'Fast food restaurant in Jeddah',
      descriptionAr: 'مطعم وجبات سريعة في جدة',
      imageUrl: 'assets/images/macdonaldes.jpg',
      category: 'food',
      distance: 2.0,
      openingHours: 'Open 24 hours',
      openingHoursAr: 'مفتوح 24 ساعة',
      latitude: 21.5117864,
      longitude: 39.2269182,
      rating: 3.9,
      mapsUrl: 'https://maps.app.goo.gl/SXNvgTXiw15RR1QLA',
    ),
    Attraction(
      id: '10',
      name: 'Historic Jeddah',
      nameAr: 'جدة التاريخية',
      description:
          'UNESCO World Heritage Site, historic old town with traditional architecture',
      descriptionAr: 'موقع تراث عالمي لليونسكو، مدينة قديمة بعمارة تقليدية',
      imageUrl: 'assets/images/historic_jeddah.jpg',
      category: 'heritage',
      distance: 3.0,
      openingHours: 'Open daily',
      openingHoursAr: 'مفتوح يومياً',
      latitude: 21.4870186,
      longitude: 39.1868741,
      rating: 4.4,
      mapsUrl: 'https://maps.app.goo.gl/Vijgxh8nPSVoGrDN7',
    ),
    Attraction(
      id: '11',
      name: 'Old Jeddah Al-Balad',
      nameAr: 'جدة القديمة البلد',
      description: 'Archaeological museum in historic district',
      descriptionAr: 'متحف أثري في الحي التاريخي',
      imageUrl: 'assets/images/old_jeddah.jpg',
      category: 'heritage',
      distance: 3.0,
      openingHours: '9:00 AM - 9:00 PM',
      openingHoursAr: '9:00 صباحاً - 9:00 مساءً',
      latitude: 21.4879841,
      longitude: 39.1855314,
      rating: 4.5,
      mapsUrl: 'https://maps.app.goo.gl/K3AtuUFsamoa5HEM6',
    ),
    Attraction(
      id: '12',
      name: 'Old Jeddah Gate (Bab Jeddah)',
      nameAr: 'باب جدة القديم',
      description: 'Historic city gate in Al-Balad',
      descriptionAr: 'بوابة المدينة التاريخية في البلد',
      imageUrl: 'assets/images/bab_jeddah.jpg',
      category: 'heritage',
      distance: 3.0,
      openingHours: 'Open 24 hours',
      openingHoursAr: 'مفتوح 24 ساعة',
      latitude: 21.4892142,
      longitude: 39.1862892,
      rating: 4.5,
      mapsUrl: 'https://maps.app.goo.gl/3kkFRjph5RriPVny9',
    ),
    Attraction(
      id: '13',
      name: 'Historic Jeddah Festival',
      nameAr: 'مهرجان جده التاريخيه',
      description: 'Cultural festival celebrating Jeddah heritage',
      descriptionAr: 'مهرجان ثقافي يحتفي بتراث جدة',
      imageUrl: 'assets/images/jeddah_event.jpg',
      category: 'events',
      distance: 3.0,
      openingHours: 'Seasonal event',
      openingHoursAr: 'فعالية موسمية',
      latitude: 21.485811,
      longitude: 39.1925048,
      rating: 4.5,
      mapsUrl: 'https://maps.app.goo.gl/HGbD3NZq9zEbHBHQ8',
    ),
    Attraction(
      id: '14',
      name: 'Bab Sharif Gate',
      nameAr: 'باب شريف',
      description: 'Historic gate in Al-Balad district',
      descriptionAr: 'بوابة تاريخية في حي البلد',
      imageUrl: 'assets/images/sharif_gate.jpg',
      category: 'heritage',
      distance: 3.0,
      openingHours: 'Open 24 hours',
      openingHoursAr: 'مفتوح 24 ساعة',
      latitude: 21.4810391,
      longitude: 39.1873745,
      rating: 4.5,
      mapsUrl: 'https://maps.app.goo.gl/2SHHpZ4YA2jaMMAs7',
    ),
    Attraction(
      id: '15',
      name: 'Jeddah Exhibition and Convention Center',
      nameAr: 'مركز جدة للمعارض والفعاليات',
      description: 'Major exhibition and events venue in Jeddah',
      descriptionAr: 'مركز رئيسي للمعارض والفعاليات في جدة',
      imageUrl: 'assets/images/jeddah_exhibition.jpg',
      category: 'events',
      distance: 1.0,
      openingHours: '9:00 AM - 9:00 PM',
      openingHoursAr: '9:00 صباحاً - 9:00 مساءً',
      latitude: 21.6168636,
      longitude: 39.1560801,
      rating: 4.2,
      mapsUrl: 'https://maps.app.goo.gl/aCEUbMmiYMCTXwMV9',
    ),
    Attraction(
      id: '16',
      name: 'Al-Rahma Mosque (Floating Mosque)',
      nameAr: 'مسجد الرحمة',
      description: 'Iconic floating mosque on the Red Sea corniche',
      descriptionAr: 'مسجد الرحمة العائم الشهير على كورنيش البحر الأحمر',
      imageUrl: 'assets/images/masjid_alrhmah.jpg',
      category: 'heritage',
      distance: 1.0,
      openingHours: 'Open 24 hours',
      openingHoursAr: 'مفتوح 24 ساعة',
      latitude: 21.6485661,
      longitude: 39.1008916,
      rating: 4.6,
      mapsUrl: 'https://maps.app.goo.gl/kqwM5CAfXSbLT1Lg9',
    ),
  ];
}
