class Attraction {
  final String id;
  final String name;
  final String nameAr;
  final String description;
  final String descriptionAr;
  final String imageUrl;
  final String category;
  final double distance;
  final String openingHours;
  final String openingHoursAr;
  final double latitude;
  final double longitude;
  final double rating;

  Attraction({
    required this.id,
    required this.name,
    required this.nameAr,
    required this.description,
    required this.descriptionAr,
    required this.imageUrl,
    required this.category,
    required this.distance,
    required this.openingHours,
    required this.openingHoursAr,
    required this.latitude,
    required this.longitude,
    required this.rating,
  });

  static List<Attraction> dummyAttractions = [
    Attraction(
      id: '1',
      name: 'Al-Masjid an-Nabawi',
      nameAr: 'المسجد النبوي',
      description: 'The Prophet\'s Mosque in Medina, one of the largest mosques in the world',
      descriptionAr: 'المسجد النبوي في المدينة المنورة، أحد أكبر المساجد في العالم',
      imageUrl: 'assets/images/mecca.jpg',
      category: 'heritage',
      distance: 2.5,
      openingHours: 'Open 24 hours',
      openingHoursAr: 'مفتوح 24 ساعة',
      latitude: 24.4672,
      longitude: 39.6111,
      rating: 4.9,
    ),
    Attraction(
      id: '2',
      name: 'Diriyah Historic District',
      nameAr: 'حي الطريف التاريخي',
      description: 'UNESCO World Heritage site and birthplace of the Saudi state',
      descriptionAr: 'موقع تراث عالمي لليونسكو ومسقط رأس الدولة السعودية',
      imageUrl: 'assets/images/balad.jpg',
      category: 'heritage',
      distance: 5.2,
      openingHours: '9:00 AM - 9:00 PM',
      openingHoursAr: '9:00 صباحاً - 9:00 مساءً',
      latitude: 24.7333,
      longitude: 46.5750,
      rating: 4.7,
    ),
    Attraction(
      id: '3',
      name: 'Edge of the World',
      nameAr: 'نهاية العالم',
      description: 'Dramatic cliff formation offering breathtaking views',
      descriptionAr: 'تكوين صخري مذهل يوفر إطلالات خلابة',
      imageUrl: 'assets/images/desset.jpg',
      category: 'nature',
      distance: 95.0,
      openingHours: 'Open daily (daylight hours)',
      openingHoursAr: 'مفتوح يومياً (ساعات النهار)',
      latitude: 24.9347,
      longitude: 46.1436,
      rating: 4.8,
    ),
    Attraction(
      id: '4',
      name: 'Al Balad Historic District',
      nameAr: 'حي البلد التاريخي',
      description: 'Historic area of Jeddah with traditional architecture',
      descriptionAr: 'منطقة تاريخية في جدة بعمارة تقليدية',
      imageUrl: 'assets/images/balad.jpg',
      category: 'heritage',
      distance: 12.8,
      openingHours: '10:00 AM - 10:00 PM',
      openingHoursAr: '10:00 صباحاً - 10:00 مساءً',
      latitude: 21.4858,
      longitude: 39.1925,
      rating: 4.6,
    ),
    Attraction(
      id: '5',
      name: 'Kingdom Centre Tower',
      nameAr: 'برج المملكة',
      description: 'Iconic skyscraper with sky bridge observation deck',
      descriptionAr: 'ناطحة سحاب شهيرة مع جسر سماوي للمراقبة',
      imageUrl: 'assets/images/riyadh.jpg',
      category: 'landmark',
      distance: 3.1,
      openingHours: '9:00 AM - 11:00 PM',
      openingHoursAr: '9:00 صباحاً - 11:00 مساءً',
      latitude: 24.7114,
      longitude: 46.6753,
      rating: 4.5,
    ),
    Attraction(
      id: '6',
      name: 'Hegra Archaeological Site',
      nameAr: 'موقع الحجر الأثري',
      description: 'Ancient Nabataean city with stunning rock-cut tombs',
      descriptionAr: 'مدينة نبطية قديمة بمقابر منحوتة في الصخر',
      imageUrl: 'assets/images/hegra.jpg',
      category: 'heritage',
      distance: 380.0,
      openingHours: '8:00 AM - 5:00 PM',
      openingHoursAr: '8:00 صباحاً - 5:00 مساءً',
      latitude: 26.7891,
      longitude: 37.9547,
      rating: 4.9,
    ),
    Attraction(
      id: '7',
      name: 'Traditional Saudi Restaurant',
      nameAr: 'مطعم سعودي تقليدي',
      description: 'Authentic Saudi cuisine with traditional flavors',
      descriptionAr: 'مطبخ سعودي أصيل بنكهات تقليدية',
      imageUrl: 'assets/images/riyadh.jpg',
      category: 'food',
      distance: 1.2,
      openingHours: '12:00 PM - 11:00 PM',
      openingHoursAr: '12:00 ظهراً - 11:00 مساءً',
      latitude: 24.7136,
      longitude: 46.6753,
      rating: 4.4,
    ),
    Attraction(
      id: '8',
      name: 'Desert Dining Experience',
      nameAr: 'تجربة تناول الطعام الصحراوية',
      description: 'Unique dining experience under the stars',
      descriptionAr: 'تجربة طعام فريدة تحت النجوم',
      imageUrl: 'assets/images/desset.jpg',
      category: 'food',
      distance: 45.0,
      openingHours: '6:00 PM - 10:00 PM',
      openingHoursAr: '6:00 مساءً - 10:00 مساءً',
      latitude: 24.5247,
      longitude: 46.8436,
      rating: 4.7,
    ),
    Attraction(
      id: '9',
      name: 'Riyadh Cultural Festival',
      nameAr: 'مهرجان الرياض الثقافي',
      description: 'Annual cultural festival with performances and exhibitions',
      descriptionAr: 'مهرجان ثقافي سنوي مع عروض ومعارض',
      imageUrl: 'assets/images/riyadh.jpg',
      category: 'events',
      distance: 8.5,
      openingHours: '4:00 PM - 11:00 PM',
      openingHoursAr: '4:00 مساءً - 11:00 مساءً',
      latitude: 24.7136,
      longitude: 46.6753,
      rating: 4.6,
    ),
    Attraction(
      id: '10',
      name: 'International Business Summit',
      nameAr: 'القمة التجارية الدولية',
      description: 'Major business conference and networking event',
      descriptionAr: 'مؤتمر أعمال رئيسي وفعالية تواصل',
      imageUrl: 'assets/images/balad.jpg',
      category: 'events',
      distance: 5.0,
      openingHours: '9:00 AM - 6:00 PM',
      openingHoursAr: '9:00 صباحاً - 6:00 مساءً',
      latitude: 24.7247,
      longitude: 46.6853,
      rating: 4.3,
    ),
  ];
}
